name: linting, testing, building
on:
   push:
     branches: [fourteen]
   pull_request:
     branches: [fourteen]
jobs:
  building:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 20.19.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod


  checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
       node-version: [20.19.0]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting css
        if: always()
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
#      - name: build storybook
#        if: always()
#        run: npm run storybook:build
#      - name: screenshot testing
#        if: always()
#        run: npm run test:ui:ci